name: test-macOS

on: [push, pull_request]

env:
  PYTHON_VERSION: 3.8
  FLAKY_TESTS: dontcare

jobs:
  test-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j8 V=1
      - name: Test
        run: make run-ci -j8 V=1 TEST_CI_ARGS="-p dots"
