name: test-asan

on: [push, pull_request]

env:
  PYTHON_VERSION: 3.8
  FLAKY_TESTS: dontcare

jobs:
  test-asan:
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++
      LINK: clang++
      CONFIG_FLAGS: --enable-asan
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j2 V=1
      - name: Test cctest
        run: make cctest -j2 V=1
